var fun = function lang(l) {
  dateformat.i18n = require('./lang/' + l)
  return true;
}
theme: [jekyll-theme-slate]
title: [The title of your site]
description: [A short description of your site's purpose]

